login:
    path: /
    controller: App\Controller\SecurityController::login
    defaults:
        title: "Real Digital | Login"

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

index:
    path: /files
    controller: App\Controller\MainController::list
    defaults:
        title: "Real Digital | Files"

new_file:
    path: /files/new
    controller: App\Controller\MainController::new
    defaults:
        title: "Real Digital | New File"

download_file:
    path: /files/download/{id}
    controller: App\Controller\MainController::download

delete_file:
    path: /files/delete/{id}
    controller: App\Controller\MainController::delete

edit_file:
    path: /files/edit
    methods: POST
    controller: App\Controller\MainController::edit
