login:
    path: /
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

index:
    path: /index
    controller: App\Controller\MainController::list

new_file:
    path: /new
    controller: App\Controller\MainController::new

download_file:
    path: /download/{id}
    controller: App\Controller\MainController::download

delete_file:
    path: /delete/{id}
    controller: App\Controller\MainController::delete

edit_file:
    path: /edit
    methods: POST
    controller: App\Controller\MainController::edit
