login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

index:
    path: /index
    controller: App\Controller\MainController::index

new_file:
    path: /new
    controller: App\Controller\MainController::newAction
